// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHcaUMxZzIgANhmtrcSlo_Y8wR9FOHsQk',
    appId: '1:921386741164:web:2476a2c3bb866d03169e09',
    messagingSenderId: '921386741164',
    projectId: 'atlcs-d5b14',
    authDomain: 'atlcs-d5b14.firebaseapp.com',
    storageBucket: 'atlcs-d5b14.firebasestorage.app',
    measurementId: 'G-C7DCFWJR2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjv3K-KTFUNArblYjP40OwjBoL9c5LXac',
    appId: '1:921386741164:android:82b169860b49f73e169e09',
    messagingSenderId: '921386741164',
    projectId: 'atlcs-d5b14',
    storageBucket: 'atlcs-d5b14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9baOFGt2Cxr4ddsPPx18w3diUxEN55BY',
    appId: '1:921386741164:ios:de8c1439faaeb1f4169e09',
    messagingSenderId: '921386741164',
    projectId: 'atlcs-d5b14',
    storageBucket: 'atlcs-d5b14.firebasestorage.app',
    iosBundleId: 'com.fluttermapp.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHcaUMxZzIgANhmtrcSlo_Y8wR9FOHsQk',
    appId: '1:921386741164:web:ede9a0ec80ea505d169e09',
    messagingSenderId: '921386741164',
    projectId: 'atlcs-d5b14',
    authDomain: 'atlcs-d5b14.firebaseapp.com',
    storageBucket: 'atlcs-d5b14.firebasestorage.app',
    measurementId: 'G-XZ6XTCPX65',
  );

}